name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test flake8 and pytest:
    runs-on: ubuntu-latest

    steps:
      -name: check code style with flake8
       run: |
         pip install flake8
         flake8 --max-line-length=120 --exclude=env,venv,.venv

      - name: run tests with pytest
        uses: actions/checkout@v2
        run: |
          python -m pip install --upgrade pip
          pip install -r api_yamdb/requirements.txt
          pytest --maxfail=1 --disable-warnings -q

  build and push Docker image:
    needs: test flake8 and pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./infra
          file: ./infra/docker-compose.yaml
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/yamdb:latest

      

